# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L9-hvKQ5ABfbUNKmN54WYk11Ym7f7Fyk
"""

import pandas as pd

df = pd.read_csv("/content/test.csv")
df

df.shape



df.columns

df.info()

df['Sex'].value_counts()

df.groupby('Sex')['Survived'].value_counts()

import matplotlib.pyplot as plt

labels = ['Female', 'Male']
survived = [233, 109]
not_survived = [81, 468]

# Create a bar chart
bar_width = 0.35
index = range(len(labels))

# Set up the plot
fig, ax = plt.subplots(figsize=(8, 6))

# Plotting the bars for survivors and non-survivors
bar1 = ax.bar(index, survived, bar_width, label='Survived', color='green')
bar2 = ax.bar([i + bar_width for i in index], not_survived, bar_width, label='Not Survived', color='red')

# Adding title and labels
ax.set_title('Survival Count by Gender')
ax.set_xlabel('Gender')
ax.set_ylabel('Count')
ax.set_xticks([i + bar_width / 2 for i in index])  # Position labels in between bars
ax.set_xticklabels(labels)

# Add a legend
ax.legend()

# Display the plot
plt.show()